name: ghcr-marimo
on:
  push:
    branches: [ "test" ]

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    if: github.repository == 'alinelena/janus-core'
    permissions:
      packages: write
      contents: read
    steps:
# free space from https://stackoverflow.com/questions/75536771/github-runner-out-of-disk-space-after-building-docker-image
      -
        name: Check disk space
        run: df . -h
      -
        name: Free disk space
        run: |
          sudo docker rmi $(docker image ls -aq) >/dev/null 2>&1 || true
          sudo rm -rf \
            /usr/share/dotnet /usr/local/lib/android /opt/ghc \
            /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup \
            /usr/lib/jvm || true
          echo "some directories deleted"
          sudo apt install aptitude -y >/dev/null 2>&1
          sudo aptitude purge aria2 ansible azure-cli shellcheck rpm xorriso zsync \
            esl-erlang firefox gfortran google-chrome-stable \
            google-cloud-sdk imagemagick \
            libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl \
            mercurial apt-transport-https mono-complete libmysqlclient \
            unixodbc-dev yarn chrpath libssl-dev libxft-dev \
            libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
            snmp pollinate libpq-dev postgresql-client powershell ruby-full \
            sphinxsearch subversion mongodb-org azure-cli microsoft-edge-stable \
            temurin-11-jdk temurin-8-jdk temurin-17-jdk temurin-21-jdk \
            llvm-16-dev llvm-17-dev llvm-18-dev \
            -y -f >/dev/null 2>&1
          sudo aptitude purge google-cloud-sdk -f -y >/dev/null 2>&1
          sudo aptitude purge microsoft-edge-stable -f -y >/dev/null 2>&1 || true
          sudo apt purge microsoft-edge-stable -f -y >/dev/null 2>&1 || true
          sudo aptitude purge '~n ^mysql' -f -y >/dev/null 2>&1
          sudo aptitude purge '~n ^php' -f -y >/dev/null 2>&1
          sudo aptitude purge '~n ^dotnet' -f -y >/dev/null 2>&1
          sudo apt-get autoremove -y >/dev/null 2>&1
          sudo apt-get autoclean -y >/dev/null 2>&1
          echo "some packages purged"
      -
        name: Check disk space
        run: |
          sudo dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -nr | head
          df . -h
          sudo du /usr/ -hx -d 4 --threshold=1G | sort -hr | head
      - name: 'clone the repo'
        uses: actions/checkout@v4
      - name: 'login to ghcr'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./containers
          file: ./containers/Dockerfile.marimo
          push: true
          tags: |
            ghcr.io/stfc/janus-core/marimo:amd64-${{ github.sha }}
            ghcr.io/stfc/janus-core/marimo:amd64-latest
  build-arm64:
    runs-on: ubuntu-24.04-arm
    if: github.repository == 'stfc/janus-core'
    permissions:
      packages: write
      contents: read
    steps:
      - name: 'clone the repo'
        uses: actions/checkout@v4
      - name: 'login to ghcr'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./containers
          file: ./containers/Dockerfile.marimo
          push: true
          tags: |
            ghcr.io/stfc/janus-core/marimo:arm64-${{ github.sha }}
            ghcr.io/stfc/janus-core/marimo:arm64-latest
